name: gsports
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.1

dependencies:
  cached_network_image: ^3.4.1
  carousel_slider: ^5.1.1
  cloud_firestore: ^6.1.0
  equatable: ^2.0.7
  firebase_auth: ^6.1.2
  firebase_core: ^4.2.1
  firebase_storage: ^13.0.4
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_dotenv: ^6.0.0
  flutter_svg: ^2.2.3
  get_it: ^9.1.1
  go_router: ^17.0.0
  google_fonts: ^6.3.3
  google_sign_in: ^7.2.0
  injectable: ^2.7.0
  intl: ^0.20.2
  json_annotation: ^4.9.0
  shimmer: ^3.0.0
  webview_flutter: ^4.13.0
  fpdart: ^1.1.0
  http: ^1.6.0
  bloc: ^9.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.0.0
  json_serializable: ^6.0.0
  mocktail: ^1.0.4
  very_good_analysis: ^10.0.0
  injectable_generator: ^2.6.1
  firebase_auth_mocks: ^0.15.1
  bloc_test: ^10.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
